type: rpm-ostree
repos:
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
install:
  - zsh
  - fzf
  - git-crypt
  - git-lfs
  - gcc
  - gcc-c++
  - neovim
  - simple-scan
  - stow
  - tmux
  - ulauncher
  - ffmpeg
  - ffmpeg-libs
  - gstreamer1-libav
  - gstreamer1-vaapi
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugin-libav
  - uxplay
  - ripgrep
  - nautilus-python
  - nextcloud-client
  - nextcloud-client-nautilus
  - openssl
  - python3-psutil
  - google-noto-emoji-color-fonts
  - mozilla-fira-mono-fonts
  - mozilla-fira-sans-fonts
  - nodejs
  - poetry
  - blackbox-terminal
  - gnome-console
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  - gnome-terminal
  - gnome-terminal-nautilus
