type: rpm-ostree
repos:
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
install:
  - zsh
  - fzf
  - git-crypt
  - neovim
  - simple-scan
  - stow
  - tmux
  - ulauncher
  - ripgrep
  - alacritty
  - nautilus-python
  - nextcloud-client
  - nextcloud-client-nautilus
  - openssl
  - python3-psutil
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  - toolbox
