type: rpm-ostree
repos:
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
install:
  - binutils
  - zsh
  - fzf
  - git-crypt
  - git-lfs
  - gcc
  - gcc-c++
  - neovim
  - simple-scan
  - stow
  - tmux
  - ulauncher
  - ffmpeg
  - ffmpeg-libs
  - gstreamer1-libav
  - gstreamer1-vaapi
  - gstreamer1-plugins-base
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-good
  - gstreamer1-plugin-libav
  - uxplay
  - ripgrep
  - nautilus-python
  - nextcloud-client
  - nextcloud-client-nautilus
  - openssl
  - python3-psutil
  - python-unversioned-command
  - google-noto-emoji-color-fonts
  - mozilla-fira-mono-fonts
  - mozilla-fira-sans-fonts
  - nodejs
  - poetry
  - luarocks
  - java-latest-openjdk
  - maven
  - blackbox-terminal
  - podman-plugins
  - podman-tui
  - podmansh
  - podman-compose
  - devpod
  - code
  - containerd.io
  - docker-ce
  - docker-ce-cli
  - docker-buildx-plugin
  - docker-compose-plugin
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-gsconnect
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-software
  - gnome-tour
  - gnome-software-rpm-ostree
